services:
  telefax:
    build: .
    container_name: telefax
    # Load environment variables from the .env file in the same directory
    env_file:
      - .env
    # Restart the container unless it's manually stopped
    restart: unless-stopped
    # Optional: Add volumes if you need persistent storage later
    volumes:
     - ./data/print_history.json:/app/print_history.json:rw
