name: Secrets Scan

on:
  push:
    branches: [ main ] # Adjust if your main branch has a different name
  pull_request:
    branches: [ main ] # Adjust if your main branch has a different name
  workflow_dispatch: # Allows manual triggering

jobs:
  scan:
    name: Gitleaks Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for Gitleaks to scan

      - name: Run Gitleaks scan
        uses: gitleaks/gitleaks-action@v2
        env:
          # If you have a Gitleaks config file (e.g., .gitleaks.toml)
          # GITLEAKS_CONFIG: .gitleaks.toml
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Optional: Upload report as artifact
          # Set GITLEAKS_LICENSE if you have a professional license
          # GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}}
